# Generated by Django 5.1.4 on 2025-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_bet_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="msg_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
