# Generated by Django 5.1.4 on 2025-02-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_bet_msg_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="symbol",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
