# Generated by Django 5.1.4 on 2025-02-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prompt",
            name="timeframe",
            field=models.CharField(max_length=4),
        ),
    ]
